"""Reporting: the master comparison table + the throughput-vs-latency curve.

Honesty rule (the project's senior signal): any report containing synthetic
rows is stamped SYNTHETIC so mock numbers are never mistaken for measured ones.
"""
from __future__ import annotations

from .. import settings
from ..schemas import BenchmarkResult

_ORDER = {"naive": 0, "vllm": 1, "awq": 2, "tuned": 3}


def master_table(results: list[BenchmarkResult], concurrency: int) -> str:
    rows = [r for r in results if r.concurrency == concurrency]
    # one row per label; keep the most recently stored
    by_label: dict[str, BenchmarkResult] = {}
    for r in rows:
        by_label[r.label] = r
    ordered = sorted(by_label.values(), key=lambda r: _ORDER.get(r.profile, 99))
    if not ordered:
        return f"No results at concurrency={concurrency}. Run `infsvc sweep` first."

    synthetic = any(r.synthetic for r in ordered)
    lines = []
    if synthetic:
        lines.append("> **SYNTHETIC - illustrative only.** Generated by the mock "
                     "performance model, not measured on a GPU.\n")
    lines.append(f"**Master comparison @ concurrency={concurrency}, "
                 f"{ordered[0].input_tokens} in / {ordered[0].output_tokens} out tokens**\n")
    header = "| system | tok/s | p99 latency (ms) | $/1k tok | GPU mem (GB) | quality | util % |"
    lines.append(header)
    lines.append("|" + "---|" * 7)
    for r in ordered:
        cost = "-" if r.cost_per_1k_usd in (0.0, float("inf")) else f"{r.cost_per_1k_usd:.4f}"
        mem = "-" if r.gpu_mem_gb is None else f"{r.gpu_mem_gb:.1f}"
        util = "-" if r.gpu_util_pct is None else f"{r.gpu_util_pct:.0f}"
        qual = "-" if r.quality is None else f"{r.quality:.3f}"
        lines.append(
            f"| {r.label} | {r.output_tok_per_s:.0f} | {r.lat_p99_ms:.0f} | "
            f"{cost} | {mem} | {qual} | {util} |"
        )
    return "\n".join(lines)


def curve_points(results: list[BenchmarkResult], profile: str) -> list[tuple[int, float, float]]:
    pts = [
        (r.concurrency, r.output_tok_per_s, r.lat_p99_ms)
        for r in results
        if r.profile == profile
    ]
    return sorted(set(pts))


def write_curve_png(results: list[BenchmarkResult], profiles: list[str], path=None) -> str | None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ModuleNotFoundError:
        return None

    settings.ensure_dirs()
    path = path or (settings.RESULTS_DIR / "throughput_latency.png")
    fig, ax = plt.subplots(figsize=(7, 5))
    for prof in profiles:
        pts = curve_points(results, prof)
        if not pts:
            continue
        tok = [p[1] for p in pts]
        lat = [p[2] for p in pts]
        ax.plot(tok, lat, marker="o", label=prof)
    ax.set_xlabel("throughput (output tokens/sec)")
    ax.set_ylabel("p99 latency (ms)")
    ax.set_title("Throughput vs. latency (SYNTHETIC)" if any(r.synthetic for r in results)
                 else "Throughput vs. latency")
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(path, dpi=120)
    plt.close(fig)
    return str(path)
